#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pathspec', 'pathspec.patterns']

package_data = \
{'': ['*']}

setup(name='pathspec',
      version='0.12.1',
      description='Utility library for gitignore style pattern matching of file paths.',
      author=None,
      author_email='"Caleb P. Burns" <cpburnz@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.8',
     )
