#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pathspec',
 'pathspec._backends',
 'pathspec._backends.hyperscan',
 'pathspec._backends.re2',
 'pathspec._backends.simple',
 'pathspec.patterns',
 'pathspec.patterns.gitignore']

package_data = \
{'': ['*']}

extras_require = \
{'hyperscan': ['hyperscan >=0.7'],
 'optional': ['typing-extensions >=4'],
 're2': ['google-re2 >=1.1'],
 'tests': ['pytest >=9', 'typing-extensions >=4.15']}

setup(name='pathspec',
      version='1.0.2',
      description='Utility library for gitignore style pattern matching of file paths.',
      author=None,
      author_email='"Caleb P. Burns" <cpburnz@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.9',
     )
